name: manga_logger
description: "An app to keep track of the manga you have!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_barcode_scanner: ^2.0.0
  flutter_markdown: ^0.7.3+1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/manga_logger.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/menu-light.svg
    - assets/icons/menu-dark.svg
    - assets/icons/profile-light.svg
    - assets/icons/profile-dark.svg
    - assets/icons/barcode-scan.svg
    - assets/privacy-policy.md

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
          weight: 700
